:doctitle:  Eric Honorez - Software Developer

ifdef::backend-pdf[:notitle:]
ifdef::backend-pdf[[discrete]]
= {doctitle}

I am a passionate developer interested about software architecture and design, domain driven design, test driven development, software craftmanship and functional programming. I like to go out of my confort zone, learn new things and share my experiences.

== Info & Contact

* 31 year old
* Located in Brussels
* e-mail: eric[dot]honorez[at]gmail[dot]com
* mobile phone: -
* twitter: https://twitter.com/eric_honorez[@eric_honorez]
* https://www.linkedin.com/in/eric-honorez-29541b19/[linkedin]
* github: https://github.com/erichonorez

== Expertise

* Software design
* Test driven development
* Domain driven design
* Functional programming
* REST APIs
* JEE
* Maven
* Git

== Experiences

=== Software developer - Technical lead
_Buy Way Services GEIE - 09/2018 to Current_

Buy Way Services GEIE is a company financed by Buy Way Personal Finance and Carrefour Finance to provide them IT solutions. Buy Way Personal Finance is a consumer loan company whose business model focus on providing financial solution to retail (e.g. Media Markt, Telenet, Ikea, Base, etc.). Carrefour Finance provides financing solutions to Carrefour's customer.

In short Buy Way Services GEIE develops and maintains IT solutions to :

* apply for a loan;
* help sales representatives to study loan application and take a decision;
* handle the life cycle of loans after their origination.

It represents an average of 600 new loans per days accross Belgium and Luxembourg.

Project: Buy Way Personal Finance wanted to offer a solution for internet payment on e-commerce websites. It offers to the customers the possibility to finance their cart by applying for a loan. This project consist of exposing a new origination business process via web API. It enables our partners to easily integrate our solution to their website. The strenght of the solution is to give real-time decisions by facilitating customer enrollment (using third party services like ItsMe) and allowing the clients to sign their contract digitally. 

Team & organisation: The development methodology was scrum. We were 4 developers, 1 scrum master and 1 product owner.

My responsibilities were to:

* help the product owner to design a business solution taking into account the technical requirements;
* design and document public APIs exposed to our partners for integration into their e-commerce website;
* design microservices behind these public APIs;
* build an API portal;
* lead a developer team of 3;
** teach them about hexagonal architecture, event-sourcing, domain driven design, test driven development, functional programming, kafka
** coach them by doing mob programming, pair programming and code review;
* development of new features;

*Technologies: Domain Driven Design, Test Driven Development, Hexagonal Architecture, REST API, microservices, event sourcing, CQRS, Spring 5, kafka, kong, vavr (functional programming in Java), git, maven, Jenkins, junit, mockito, cucumber, docker, linux.*

=== Software developer - Technical lead
_Buy Way Services GEIE - from 01/2017 to 09/2018_

Buy Way Personal Finance wanted to reduce the operational cost of loan application by digitalising the process. The digitialisation reduces the operational cost by:

* capturing all evidences and extracting information using OCR and validating them;
* signing digitally the contract using Qualified Electronic Signature or Advanced Electronic Signature.

The implementation of this new business process had to follow the new target architecture (see <<bw-sofware-architect, below>>).

Team & organisation : The development methodology was scrum. We were 8 developers, 1 scrum master, 1 functional analyst, 1 project manager.

My responsibilities were to:

* capture the functional requirements based on business analysis;
* design software architecture;
* analysis of integrations with third party services:
** Documentum - entreprise content management platform used stored evidences and contract signed digitally;
** Captiva - OCR engine integrated with Documentum used in order to validate evidences;
** OneSpan E-Signatures - Advanced Electronic Signature tool used to sign contracts;
* design REST APIs;
* recrutment and technical interviews of new developers;
* lead a team of 7 developers;
* development of new features;
* release and deploy the new components on the several environments.

*Technologies: microservices, event sourcing, CQRS, Spring 4, kafka, git, maven, Jenkins, junit, mockito, cucumber, docker, linux, asciidoc.*

=== [#bw-software-architect]#Software Architect#
_Buy Way Services GEIE - from 01/2017 to 09/2018_

In order to support Buy Way Personal Finance's digital ambitions and enable new business models based on APIs, the current architecture of Java applications had to evolve. Many components of the actual monolithic system relied on out-of-date technologies and everything was tightly coupled. It made the system hard to change and hard to exposed through REST APIs to external parties. 

Team & organisation: 1 the enterprise architect, 1 strategy manager and an external consultancy company (BCG Platinion).

My responsibilities were to:

* design a new software architecture that would allow modernisation and modularisation;
** The target architecture was a event-driven microservice architecture based on Apache Kafka and Spring.
* organise the progressive migration from the monolithic application to this target architecture;
* design new services high-level APIs;
* define new development standard for micro-services;
* report to top management;

*Technologies: microservices, distributed systems, event sourcing, CQRS, kafka.*

=== Java Software developer 
_Buy Way Services GEIE - 05/2014 to 06/2017_

My job was to analyse, estimate and implement new features for origination applications:

Team & organisation: ~20 developers splitted accross 5 scrum teams.

My responsibilities were to:

* web application in order to apply for loan application directly from a e-commerce web site;
* digital signature based on the Belgian id card to sign contracts;
* document management system in order to handle the digitialisation of loan contracts;
* customisation of existing loan application flow for specific customers;


*Technolgies: JEE 7 stack (EJB, CDI, JMS, JPA, JAX-RS, JAX-B), Vaadin 6, maven, git, jenkins, oracle, junit, mockito, cucumber, selenium, Glassfish 3, Wildfly 10, docker, gerrit, linux.*

=== Part-time release manager 
_Buy Way Services GEIE - 01/2016 to 06/2017_

Beside beeing software developer I also had to opportunity to be responsible of the release of our applications. We had two releases of our applications per month (hotfix versions not included).

My responsibilities were to:

** deploy the release candidate in Staging environment;
** be sure that all features in the release candidate have received the approval from testers to be deployed in production;
** prepare and version all the deployable artifacts;
** prepare the deployment guide;
** maintain and evolve the version control branching model depdending on the needs;
** code review.

*Technologies: maven, git, gerrit, linux, jenkins.*

=== Part-time scrum master
_Buy Way Services GEIE - 01/2015 - 12/2015_

Beside beeing software developer I had the opportunity to be the part time Scrum master of a team of 6 developers. My responsibilities were to be sure that Scrum practices were correctly applied. I organised the scrum ceremonies (daily stand-up, sprint review, sprint retrospective and sprint planning), maintained the sprint backlog and generated the sprint metrics (sprint burndown chart).

Additionnally I also organised Scrum presentations for new developers.

=== Full-stack Developer
_Adneom (internal project) - 11/2013 to 05/2014_

HR team of adneom needed a tool to improve the follow-up of consultant’s evaluations during theirs missions and their career evolution.

My responsiblities were:

* application development
* writing functional and technical analysis
* integration of the tool inside the enterprise portal

*Technologies: rest api, angular js, mysql, java, spring, html 5, javascript, css3, angular js, jquery, less, twitter bootstrap, bower, responsive design*

=== Front-end Developer 
_BNP Paribas Fortis (as consultant for Adneom) - 06/2013 to 11/2013_

In the Direct Channels  Planning & Development department, my role were to help to improve the multi-channels experience of customers and raise sales through digital channels. More especially my tasks are:

* Technical analysis and end-to-end development of online projects. Eg:
** BNP Paribas Fortis webshops (on the site and in the Easy Banking mobile application)
** Direct sales
* Work out the online customer experience
* Landing pages integration (slicing)
* Marketing email campaigns development

*Technologies: angular js, html5, javascript, css3, jquery, underscore js, less, twitter bootstrap, responsive design, messagent, photoshop*

=== Front-end Developer
_BPOST (as consultant for Adneom) - 05/2013 - 06/2013_

Development of the BPOST IPO dedicated website. More especially my tasks were:

* Design slicing and integration
* Content integration

*Technologies: html, css, twitter bootstrap, jquery, photoshop*

=== Full-Stack .NET Developer
_Delhaize Group (as consultant for Adneom) - 02/2013 – 05/2013_

In a team of 5 persons (developers, tester and project manager) I was involved in the development of a Projects and Portfolios web management tool used by Delhaize Group project managers to track, plan and control theirs projects (Prince 2 inspired).

My responsibilities were:

* from scratch development of the backend and frontend
* SQL stored procedures and functions development
* fontend and backend performances optimization
* bug fixing

*Technologies: asp.net mvc4, entity framework 5, ms sql, html, css, javascript, jquery*

=== .NET Developer 
_SNCB Holding - 01/2012 to 02/2013_

My role in the SharePoint Competence Center was the end-to-end development of custom business solutions for all SNCB department and based on the SharePoint platform.

My responsibilities were:

* end-to-end development of custom solutions based on Microsoft SharePoint 2010 E.g. :
** personal Health Care portal for all SNCB employees (.NET solution integrated in SharePoint)
** ICTRA intranet (branding solution)
** document Management solutions (for HR department and Infrabel)
* writing of development, deployment, configuration and user guides
* testing

*Technologies: c#, javascript, html, css, sql, xml, xslt, sharepoint 2010, ms sql, .net, asp.net, entity framework, sharepoint om, knockout js*

=== PHP Developper
_SNCB Holding - 08/2010 – 12/2011_

My main role as developer in the PHP Competence Center was the end-to-end development of custom business solutions for all SNCB departments.

My responsibilities were:

* end-to-end development of custom solutions based on the LAMP Stack. Eg:
** event organization tool for stations
** risk analysis tool
** infrastructure tools
* writing functional and technical analysis 
* development for the Open Source Competence Center (Internal framework maintenance, evolution and optimization, new libraries and frameworks developments)
* peer coaching of developers

*Technologies: php, javascript, html, css, sql, xml, uml, mysql, zend framework, doctrine, symfony, jquery, solr search engine, ext js, jenkins, php unit*

==== System and Network Technician 
_G.E.E.IT SARL - 10/2007 to 06/2009_

In part time and in parallel of my studies I participated to the day to day maintenance and evolution of the enterprise’s clients network services.
    
* System administration (+/- 50 GNU/Linux servers 
* Network services administration such as DNS, DHCP, Apache, MySQL, SMTP, etc.
* Work in datacenters
* Monitoring

*Technologies: gnu/linux, windows server 2003, dns, dhcp, apache, mysql, smtp, ntfs, smb, ipv4, nagios, cacti, munin*

== Languages

|===
| Language | Writing | Speaking

| French
| native
| native

| English
| Fluent
| Fluent

| Dutch
| Basic
| Basic

|=== 

== Education, trainings, conferences and certifications

* 02/2018: Domain Driven Design Europe
* 11/2017: Devoxx Belgium
* 12/2016: Building Distributed Pipelines for Data Science Using Kafka, Spark, and Cassandra (O'Reilly)
* 11/2016: Devoxx Belgium
* 11/2016: Functional Programming Design in Scala (Coursera certification)
* 10/2016: Functional Programming Principles in Scala (Coursera certification)
* 11/2015: Devoxx Belgium
* 06/2015: Certified ScrumMaster (CSM)
* 02/2013: Programming in HTML5 with JavaScript and CSS3 Specialist (Microsoft certification)
* 06/2010: Bachelor degree in computer science and communication systems

== Hobbies

* Running
* Swimming
* Cycling
